# Generated by Django 3.2 on 2022-03-25 18:53

from django.db import migrations, models
import me.models.abouts
import me.models.works


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pictuer', models.ImageField(blank=True, null=True, upload_to=me.models.abouts.path_to_save)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('pictuer', models.ImageField(upload_to=me.models.works.path_to_save)),
            ],
        ),
    ]
